name: deploy

on:
  pull_request:
    types:
      - closed
      - synchronize

jobs:
  build:
    name: Deployment for Develop environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Deploy
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} --only hosting:develop
